### PR TITLE
Restart tomcat8 failed

### PR DESCRIPTION
**Pull request by DigitLib**
This PR add a /handler/main.yml which is missing to execute notify: restart tomcat8 from /tasks/config.yml

### CODE REVIEW

**Comment by whikloj** [comment]
@jonathangreen oh wise and powerful ansible master, would defining this handler here be okay?

**Comment by jonathangreen** [comment]
haha. That gives me wayy to much credit. But here are my thoughts: 

Redefining this here works, but is kind of a kluge. We define this handler here: 
https://github.com/Islandora-Devops/ansible-role-tomcat8/blob/master/handlers/main.yml#L3

Only one handler can have the same name, so by naming this the same, only one handler fires, however between the two the one that fires is the one that is referenced first [[1]](http://docs.ansible.com/ansible/latest/playbooks_intro.html) [[2]](https://github.com/ansible/ansible/issues/4943). So although this works, its kind of a trap, because if the handlers diverge, only one fires... *and then you spend hours debugging why the thing you added to the handler isn't firing and arrrgh what only one fires why do we have two 🔥:fire:?!?! (Talking from personal experience here)*

I think I'd day maybe make a note in the role that it depends on a tomcat roles for a handler named whatever to restart tomcat. When its used with our default tomcat role it should work. Or each role could have a uniquely named tomcat handler... but that get ugly because then we restart tomcat multiple times. 

I think handler sharing in general is an ansible weakness right now.

**Comment by jonathangreen** [comment]
Another thing I've seen people do is make a handler role, that contains all the shared handlers, and include that as either an implicit or explicit dependancy of the roles that share handlers... maybe that would be a solution here.

**Comment by jonathangreen** [comment]
@DigitLib I believe I fixed this issue in #5, can you check?

**Comment by DigitLib** [comment]
@jonathangreen tested #5 on CentOS and work!

**Comment by whikloj** [comment]
@DigitLib if #5 resolves this issue and the one in #3. Can we close those PRs?

**Comment by DigitLib** [comment]
@whikloj Yes.

**Comment by whikloj** [comment]
👍  thanks @DigitLib I'll close this and #3 and test #5 for merging.

**Pull request closed without merging**
