### PR TITLE
Master -> Main Rename

### PR DESCRIPTION
**Pull request by dannylamb**
Part of https://github.com/Islandora/documentation/issues/1595

### CODE REVIEW

**Comment by rosiel** [comment]
> TASK [role_under_test : Wait for Blazegraph to come up] ************************
> 
> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'tomcat'\n\nThe error appears to be in '/etc/ansible/roles/role_under_test/tasks/namespace.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Wait for Blazegraph to come up\"\n  ^ here\n"}



It's failing and I don't understand why. The last time a PR was merged here, travis also failed, but you forced it because you tested with a different version of the playbook. Is that codependency between playbook and ansible role what's causing this to barf? (though it's not even on any of our changes)

**Comment by dannylamb** [comment]
I think it's been busted for a while.  I'll have to look into it.

**Comment by rosiel** [comment]
Given that the changes clearly didn't break it, can I merge anyway?

**Comment by dannylamb** [comment]
Yes. Feel free to merge if the test failures have nothing to do with this PR.  That's OK as per our contributing workflow.

**Review by rosiel — APPROVED** [review]

**Pull request merged**
